---
- name: create /srv/nginx
  file: path=/srv/nginx state=directory
- name: copy nginx cts config
  copy: src=files/nginx.conf dest=/srv/nginx/nginx.conf
- name: start nginx docker container
  docker_container:
    api_version: 1.19
    image: nginx
    name: nginx
    network_mode: host
    volumes:
    - /srv/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - /srv/cts/static:/usr/share/nginx/html/cts
